name: Lint Markdown with proselint

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install proselint
        run: pip install proselint

      - name: Run proselint on .md files
        run: |
          find . -name "*.md" -print0 | xargs -0 proselint

