name: ShellCheck

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck on all .sh files
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck || exit 1

